# Translations template for Hue.
# Copyright (C) 2017 Cloudera, Inc
# This file is distributed under the same license as the Hue project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2017.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Hue VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-10-17 16:28-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.6\n"

#: src/hadoop/conf.py:66
msgid "NameNode logical name."
msgstr ""

#: src/hadoop/conf.py:107
msgid "JobTracker logical name."
msgstr ""

#: src/hadoop/conf.py:136
msgid "Resource Manager logical name."
msgstr ""

#: src/hadoop/fs/hadoopfs.py:287
#, python-format
msgid "%(remote_dst)s already exists. Skipping."
msgstr ""

#: src/hadoop/fs/hadoopfs.py:290
#, python-format
msgid "%(remote_dst)s does not exist. Trying to copy."
msgstr ""

#: src/hadoop/fs/hadoopfs.py:300
#, python-format
msgid "Copied %s -> %s."
msgstr ""

#: src/hadoop/fs/hadoopfs.py:302
#, python-format
msgid "Copying %s -> %s failed."
msgstr ""

#: src/hadoop/fs/hadoopfs.py:307
#, python-format
msgid "Skipping %s (not a file)."
msgstr ""

#: src/hadoop/fs/hadoopfs.py:343 src/hadoop/fs/hadoopfs.py:346
#: src/hadoop/fs/hadoopfs.py:349 src/hadoop/fs/hadoopfs.py:352
#: src/hadoop/fs/hadoopfs.py:355 src/hadoop/fs/hadoopfs.py:358
#: src/hadoop/fs/hadoopfs.py:361
#, python-format
msgid "%(function)s has not been implemented."
msgstr ""

#: src/hadoop/fs/upload.py:66
msgid "No HDFS found"
msgstr ""

#: src/hadoop/fs/upload.py:77
#, python-format
msgid "User %s does not have permissions to write to path \"%s\"."
msgstr ""

#: src/hadoop/fs/webhdfs.py:239 src/hadoop/fs/webhdfs.py:275
#, python-format
msgid "File %s not found"
msgstr ""

#: src/hadoop/fs/webhdfs.py:278
#, python-format
msgid "File %s is a directory"
msgstr ""

#: src/hadoop/fs/webhdfs.py:281
#, python-format
msgid "File %s is already trashed"
msgstr ""

#: src/hadoop/fs/webhdfs.py:308
#, python-format
msgid "Delete failed: %s"
msgstr ""

#: src/hadoop/fs/webhdfs.py:337
#, python-format
msgid "File %s is not in trash"
msgstr ""

#: src/hadoop/fs/webhdfs.py:351
#, python-format
msgid "Path %s already exists."
msgstr ""

#: src/hadoop/fs/webhdfs.py:379
#, python-format
msgid "Mkdir failed: %s"
msgstr ""

#: src/hadoop/fs/webhdfs.py:393
#, python-format
msgid "Rename failed: %s -> %s"
msgstr ""

#: src/hadoop/fs/webhdfs.py:399 src/hadoop/fs/webhdfs.py:403
#, python-format
msgid "'%s' is not a directory"
msgstr ""

#: src/hadoop/fs/webhdfs.py:580
#, python-format
msgid "Copy src '%s' does not exist"
msgstr ""

#: src/hadoop/fs/webhdfs.py:582
#, python-format
msgid "Copy src '%s' is a directory"
msgstr ""

#: src/hadoop/fs/webhdfs.py:584
#, python-format
msgid "Copy dst '%s' is a directory"
msgstr ""

#: src/hadoop/fs/webhdfs.py:665
#, python-format
msgid "File not found: %s"
msgstr ""

#: src/hadoop/fs/webhdfs.py:681
#, python-format
msgid "Destination file %s exists and is not a directory."
msgstr ""

#: src/hadoop/fs/webhdfs.py:723
#, python-format
msgid "Failed to create '%s'. HDFS did not return a redirect"
msgstr ""

#: src/hadoop/fs/webhdfs.py:789
msgid "Failed to upload file. WebHdfs requires a valid username to upload files."
msgstr ""

#: src/hadoop/fs/webhdfs.py:813
#, python-format
msgid "Is a directory: '%s'"
msgstr ""

#: src/hadoop/fs/webhdfs.py:831
msgid "Invalid argument to seek for whence"
msgstr ""

#: src/hadoop/fs/webhdfs.py:851
msgid "File not open for writing"
msgstr ""

#: src/hadoop/fs/webhdfs.py:897
#, python-format
msgid "Filesystem root '/' should be owned by '%s'"
msgstr ""

#: src/hadoop/fs/webhdfs.py:900
msgid "Failed to access filesystem root"
msgstr ""

#: src/hadoop/fs/webhdfs.py:908
#, python-format
msgid "Failed to create temporary file \"%s\""
msgstr ""

#: src/hadoop/fs/webhdfs.py:924
#, python-format
msgid "Failed to remove temporary file \"%s\""
msgstr ""

#: src/hadoop/yarn/history_server_api.py:46
msgid "YARN cluster is not available."
msgstr ""

#: src/hadoop/yarn/mapreduce_api.py:47
#: src/hadoop/yarn/resource_manager_api.py:51
msgid "No Resource Manager are available."
msgstr ""

#: src/hadoop/yarn/resource_manager_api.py:137
msgid "YARN did not return any token field."
msgstr ""

#: src/hadoop/yarn/resource_manager_api.py:175
#, python-format
msgid "Failed to resolve YARN RM: %s"
msgstr ""

#: src/hadoop/yarn/resource_manager_api.py:177
#, python-format
msgid "YARN RM returned a failed response: %s"
msgstr ""

#: src/hadoop/yarn/spark_history_server_api.py:47
msgid "No Spark History Server is available."
msgstr ""

