# Japanese translations for Hue.
# Copyright (C) 2012 Cloudera, Inc
# This file is distributed under the same license as the Hue project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2012.
#
msgid ""
msgstr ""
"Project-Id-Version: Hue VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-10-17 16:28-0400\n"
"PO-Revision-Date: 2012-11-07 13:06-0800\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: ja <LL@li.org>\n"
"Plural-Forms: nplurals=1; plural=0\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.6\n"

#: src/hadoop/conf.py:66
msgid "NameNode logical name."
msgstr "NameNode の論理名です。"

#: src/hadoop/conf.py:107
msgid "JobTracker logical name."
msgstr "JobTracker の論理名です。"

#: src/hadoop/conf.py:136
msgid "Resource Manager logical name."
msgstr "Resource Manager の論理名。"

#: src/hadoop/fs/hadoopfs.py:287
#, python-format
msgid "%(remote_dst)s already exists. Skipping."
msgstr "%(remote_dst)s はすでに存在します。スキップします。"

#: src/hadoop/fs/hadoopfs.py:290
#, python-format
msgid "%(remote_dst)s does not exist. Trying to copy."
msgstr "%(remote_dst)s が存在しません。コピーを試行しています。"

#: src/hadoop/fs/hadoopfs.py:300
#, python-format
msgid "Copied %s -> %s."
msgstr "コピー %s -> %s が完了しました。"

#: src/hadoop/fs/hadoopfs.py:302
#, python-format
msgid "Copying %s -> %s failed."
msgstr "コピー %s -> %s に失敗しました。"

#: src/hadoop/fs/hadoopfs.py:307
#, python-format
msgid "Skipping %s (not a file)."
msgstr "%s をスキップします（ファイルではありません）。"

#: src/hadoop/fs/hadoopfs.py:343 src/hadoop/fs/hadoopfs.py:346
#: src/hadoop/fs/hadoopfs.py:349 src/hadoop/fs/hadoopfs.py:352
#: src/hadoop/fs/hadoopfs.py:355 src/hadoop/fs/hadoopfs.py:358
#: src/hadoop/fs/hadoopfs.py:361
#, python-format
msgid "%(function)s has not been implemented."
msgstr "%(function)s は実装されていません。"

#: src/hadoop/fs/upload.py:66
msgid "No HDFS found"
msgstr ""

#: src/hadoop/fs/upload.py:77
#, python-format
msgid "User %s does not have permissions to write to path \"%s\"."
msgstr ""

#: src/hadoop/fs/webhdfs.py:239 src/hadoop/fs/webhdfs.py:275
#, python-format
msgid "File %s not found"
msgstr "ファイル %s が見つかりません"

#: src/hadoop/fs/webhdfs.py:278
#, python-format
msgid "File %s is a directory"
msgstr "ファイル %s はディレクトリです"

#: src/hadoop/fs/webhdfs.py:281
#, python-format
msgid "File %s is already trashed"
msgstr "ファイル %s はすでにゴミ箱に入れられています"

#: src/hadoop/fs/webhdfs.py:308
#, python-format
msgid "Delete failed: %s"
msgstr "削除に失敗しました：%s"

#: src/hadoop/fs/webhdfs.py:337
#, python-format
msgid "File %s is not in trash"
msgstr "ファイル %s はゴミ箱にありません"

#: src/hadoop/fs/webhdfs.py:351
#, python-format
msgid "Path %s already exists."
msgstr "パス %s はすでに存在します。"

#: src/hadoop/fs/webhdfs.py:379
#, python-format
msgid "Mkdir failed: %s"
msgstr "mkdir に失敗しました：%s"

#: src/hadoop/fs/webhdfs.py:393
#, python-format
msgid "Rename failed: %s -> %s"
msgstr "名前の変更 %s -> %s に失敗しました"

#: src/hadoop/fs/webhdfs.py:399 src/hadoop/fs/webhdfs.py:403
#, python-format
msgid "'%s' is not a directory"
msgstr "'%s' はディレクトリではありません"

#: src/hadoop/fs/webhdfs.py:580
#, python-format
msgid "Copy src '%s' does not exist"
msgstr "コピー元 '%s' は存在しません"

#: src/hadoop/fs/webhdfs.py:582
#, python-format
msgid "Copy src '%s' is a directory"
msgstr "コピー元 '%s' はディレクトリです"

#: src/hadoop/fs/webhdfs.py:584
#, python-format
msgid "Copy dst '%s' is a directory"
msgstr "コピー先 '%s' はディレクトリです"

#: src/hadoop/fs/webhdfs.py:665
#, python-format
msgid "File not found: %s"
msgstr "ファイルが見つかりません：%s"

#: src/hadoop/fs/webhdfs.py:681
#, python-format
msgid "Destination file %s exists and is not a directory."
msgstr "宛先ファイル %s が存在し、これはディレクトリではありません。"

#: src/hadoop/fs/webhdfs.py:723
#, python-format
msgid "Failed to create '%s'. HDFS did not return a redirect"
msgstr "'%s' の作成に失敗しました。HDFS はリダイレクトを返しませんでした"

#: src/hadoop/fs/webhdfs.py:789
msgid "Failed to upload file. WebHdfs requires a valid username to upload files."
msgstr ""

#: src/hadoop/fs/webhdfs.py:813
#, python-format
msgid "Is a directory: '%s'"
msgstr "ディレクトリです：'%s'"

#: src/hadoop/fs/webhdfs.py:831
msgid "Invalid argument to seek for whence"
msgstr "場所を検索する引数が無効です"

#: src/hadoop/fs/webhdfs.py:851
msgid "File not open for writing"
msgstr "ファイルが書き込み用に開かれていません"

#: src/hadoop/fs/webhdfs.py:897
#, fuzzy, python-format
msgid "Filesystem root '/' should be owned by '%s'"
msgstr "ファイルシステムのルート '/' は、'hdfs' によって所有されている必要があります"

#: src/hadoop/fs/webhdfs.py:900
msgid "Failed to access filesystem root"
msgstr "ファイルシステムのルートへのアクセスに失敗しました"

#: src/hadoop/fs/webhdfs.py:908
#, python-format
msgid "Failed to create temporary file \"%s\""
msgstr "一時ファイル \"%s\" の作成に失敗しました"

#: src/hadoop/fs/webhdfs.py:924
#, python-format
msgid "Failed to remove temporary file \"%s\""
msgstr "一時ファイル \"%s\" の削除に失敗しました"

#: src/hadoop/yarn/history_server_api.py:46
msgid "YARN cluster is not available."
msgstr ""

#: src/hadoop/yarn/mapreduce_api.py:47
#: src/hadoop/yarn/resource_manager_api.py:51
msgid "No Resource Manager are available."
msgstr "使用できる Resource Manager がありません。"

#: src/hadoop/yarn/resource_manager_api.py:137
msgid "YARN did not return any token field."
msgstr ""

#: src/hadoop/yarn/resource_manager_api.py:175
#, fuzzy, python-format
msgid "Failed to resolve YARN RM: %s"
msgstr "一時ファイル \"%s\" の削除に失敗しました"

#: src/hadoop/yarn/resource_manager_api.py:177
#, python-format
msgid "YARN RM returned a failed response: %s"
msgstr ""

#: src/hadoop/yarn/spark_history_server_api.py:47
msgid "No Spark History Server is available."
msgstr ""

